### ISSUE TITLE
Adding license

### ISSUE THREAD

**Issue by dkgaraujo** [dhopp1/nowcasting_benchmark#1]
Congratulations on this excellent material! 

May I suggest you add a license to your code? While sharing it on GitHub allows for code transparency, the absence of a license does not mean that it is free to use - [the contrary, in fact](https://choosealicense.com/no-permission/). Since your intention (judging by your paper) is that the code is usable by other researchers/institutions, I would suggest you consider adding a license to the repository. A good primer is GitHub's own guide, https://choosealicense.com/.

Thanks and happy to discuss.

**Comment by dhopp1** [comment]
Thank you, you are absolutely right. I intended to include the MIT license in the initial commit, but left it out in oversight. I've added now. I'm glad you found the repository interesting, thanks again for your suggestion.
