### ISSUE TITLE
Duplicate lstm model questions, request answers! Thank you so much!

### ISSUE THREAD

**Issue by diamond-jlu** [dhopp1/nowcasting_benchmark#2]
series	name	freq	block_g	block_s	block_r	block_l	months_lag
What are the next four columns of data in meta_data? Can the lstm model be used to predict the explained variables of the cycle and day degrees? What parts of the model need to change besides the data set? This question is for academic modeling, not for any other purpose! If you can answer my question, I would be very grateful!

**Comment by dhopp1** [comment]
There are no more columns in the metadata file, that is everything. You can see all the data [here](https://github.com/dhopp1/nowcasting_benchmark/tree/main/data). I'm not sure what you mean by "cycle and day degrees", but if you're asking if the LSTM can be used with daily data, yes. Here is an example:

```
import numpy as np
import pandas as pd
from nowcast_lstm.LSTM import LSTM

# generating example data
dates = list(pd.date_range("2020-01-01", "2024-01-31",freq = "d"))
n_features = 3
data = pd.DataFrame(np.random.rand(len(dates), n_features))
data.columns = ["feature_" + str(i) for i in range(1, n_features+1)]
data["date"] = dates
data = data.loc[:, ["date"] + list(data.columns[:-1])]

target_variable = "feature_3"
data.loc[~data.date.dt.is_month_end, target_variable] = np.nan

# training data up to 2023
train = data.loc[data.date < "2024-01-01", :]

# test data
test = data.copy()
test.loc[data.date >= "2024-01-01", data.columns[1:]] = np.nan # make sure no 2024 data available

# training a model
model = LSTM(
    data = train,
    target_variable = target_variable,
    n_timesteps = 30, # training based on prior 30 days' worth of data
    n_models = 10,
    train_episodes = 50,
    batch_size = int(len(data)/4)
)
model.train()

# if you predict on the test data you can see daily predictions are available
model.predict(test)
```

You can see a detailed list of the parameters in the LSTM model in the library's [README](https://github.com/dhopp1/nowcast_lstm).

**Comment by diamond-jlu** [comment]
Hello! Dear Professor Daniel Hopp, may I ask you what these columns (block_g block_s block_r block_l months_lag) in your dataset meta_data.csv mean? I wanted to create my own data set to build the model, and I used the daily frequency and the weekly frequency data to predict the weekly frequency data.
![Uploading 微信图片_20231204224411.png…]()

**Comment by dhopp1** [comment]
Ah, the `block_g block_s block_r block_l` you don't have to worry about for the LSTM, they are only for the dynamic factor model. `months_lag` is how much delay each of your series have when being published. It is important to know for testing your model. In your case, you can interpret it as `days_lag`. So if the data for January 1st is published on January 11th, you can put `10` there, because the data is published 10 days after the the fact.

**Comment by L-Neur0** [comment]
Dear professor, I am trying to replicate using the dfm. I am using weekly data and I am trying to setup the meta data csv file. First question, can I use weekly data with the dfm? :)
Second question, as mentioned upwards I can use the monthly lag column as weekly lags? In addition, in my dataset I do not have groups, I can try to train a model with only the global factor? thank you very much

**Comment by dhopp1** [comment]
Hi, no unfortunately the DFM model only works for monthly and quarterly data. However, if you are working exclusively with weekly data, i.e., trying to predict a weekly indicator with weekly data, you can still use it. You just have to change the date column to monthly dates. E.g. if you have:

date | indicator1 | indicator2
-- | -- | --
2024-11-04 | 10 | 11
2024-11-11 | 12 | 9
...

just relabel it as
date | indicator1 | indicator2
-- | -- | --
2024-01-01 | 10 | 11
2024-02-01 | 12 | 9

You can use any monthly dates, it doesn't matter, it's just so the code will run. Then you'll obviously have to keep track yourself that 2024-11-04 = 2024-01-01.

Yes you can just use 1 global block, that corresponds to `block_g` in the [metadata file](https://github.com/dhopp1/nowcasting_benchmark/blob/main/data/meta_data.csv).

**Comment by L-Neur0** [comment]
ok thank you very much, the same thing could work also with daily data, right? it just predict the daily indicator

**Comment by dhopp1** [comment]
Yes just do the same approach. Or you could try one of the methods that are compatible with daily/weekly data natively, like the [LSTM](https://github.com/dhopp1/nowcasting_benchmark/blob/main/methodologies/model_lstm_r.ipynb) or [ElasticNet](https://github.com/dhopp1/nowcasting_benchmark/blob/main/methodologies/model_elasticnet.ipynb).
